src/BankDeposits.Razor/Models/DepositViewModel.cs
namespace BankDeposits.Razor.Models;

public class DepositViewModel
{
    public Guid Id { get; init; }
    public Guid AccountId { get; init; }
    public DateTime StartDate { get; init; }
    public DateTime EndDate { get; init; }
    public decimal Rate { get; init; }
    public decimal Amount { get; init; }
    public decimal Profit { get; init; }
}

src/BankDeposits.Razor/Pages/Accounts/Create.cshtml.cs
using BankDeposits.Domain.Models;
using BankDeposits.Domain.Services.Interfaces;
using BankDeposits.Razor.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Caching.Memory;

namespace BankDeposits.Razor.Pages.Accounts;

public class AccountsCreatePageModel : PageModel
{
    private readonly ILogger<AccountsCreatePageModel> _logger;
    private readonly IAccountService _accountService;
    private readonly IDepositorService _depositorService;
    private readonly IMemoryCache _memoryCache;

    public AccountsCreatePageModel(ILogger<AccountsCreatePageModel> logger, IAccountService accountService, IDepositorService depositorService, IMemoryCache memoryCache)
    {
        _logger = logger;
        _accountService = accountService;
        _depositorService = depositorService;
        _memoryCache = memoryCache;
    }

    [BindProperty]
    public AccountCreateModel Account { get; set; } = new();

    public SelectList Depositors { get; set; } = default!;

    public async Task OnGetAsync() => await PopulateDepositorsAsync();

    public async Task<IActionResult> OnPostAsync()
    {
        if (!await VerifyNumber(Account.Number))
        {
            ModelState.AddModelError("Account.Number", "Account with this number already exists");
        }

        if (ModelState.IsValid)
        {
            var account = new Account
            {
                OwnerId = Account.OwnerId,
                Number = Account.Number,
                Balance = Account.Balance
            };

            await _accountService.AddAsync(account);

            return RedirectToPage("./Index");
        }

        await PopulateDepositorsAsync();

        return Page();
    }

    private async Task PopulateDepositorsAsync()
    {
        if (!_memoryCache.TryGetValue("DepositorsList", out SelectList? cachedDepositors))
        {
            var depositors = await _depositorService.GetAllAsync();
            cachedDepositors = new SelectList(depositors, nameof(Depositor.Id), nameof(Depositor.FullName));
            _memoryCache.Set("DepositorsList", cachedDepositors, new MemoryCacheEntryOptions().SetAbsoluteExpiration(TimeSpan.FromMinutes(5)));
        }

        Depositors = cachedDepositors!;
    }

    private async Task<bool> VerifyNumber(string number)
    {
        var account = await _accountService.GetByNumberAsync(number);
        return account is null;
    }
}

src/BankDeposits.Razor/Pages/Accounts/Details.cshtml.cs
using BankDeposits.Domain.Services.Interfaces;
using BankDeposits.Razor.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BankDeposits.Razor.Pages.Accounts;

public class AccountDetailsPageModel : PageModel
{
    private readonly ILogger<AccountDetailsPageModel> _logger;
    private readonly IAccountService _accountService;

    public AccountDetailsPageModel(ILogger<AccountDetailsPageModel> logger, IAccountService accountService)
    {
        _logger = logger;
        _accountService = accountService;
    }

    public AccountViewModel Account { get; set; } = new();

    public async Task<IActionResult> OnGetAsync(Guid id)
    {
        var account = await _accountService.GetAsync(id);
        Account = new AccountViewModel
        {
            Id = account.Id,
            OwnerId = account.OwnerId,
            Balance = account.Balance,
            Number = account.Number,
            TotalProfit = account.TotalProfit
        };

        return Page();
    }

    public async Task<IActionResult> OnPostDeleteAsync(Guid id)
    {
        await _accountService.DeleteAsync(id);
        return RedirectToPage("./Index");
    }
}

src/BankDeposits.Razor/Pages/Accounts/Edit.cshtml.cs
using BankDeposits.Domain.Services.Interfaces;
using BankDeposits.Razor.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BankDeposits.Razor.Pages.Accounts;

public class AccountsEditPageModel : PageModel
{
    private readonly ILogger<AccountsEditPageModel> _logger;
    private readonly IAccountService _accountService;

    public AccountsEditPageModel(ILogger<AccountsEditPageModel> logger, IAccountService accountService)
    {
        _logger = logger;
        _accountService = accountService;
    }

    [BindProperty]
    public AccountEditModel Account { get; set; } = new();

    public async Task<IActionResult> OnGetAsync(Guid id)
    {
        var account = await _accountService.GetAsync(id);
        Account = new AccountEditModel
        {
            Id = account.Id,
            Balance = account.Balance,
        };

        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }

        var account = await _accountService.GetAsync(Account.Id);

        account.Balance = Account.Balance;

        await _accountService.UpdateAsync(account);

        return RedirectToPage("./Details", new { id = Account.Id });
    }
}

src/BankDeposits.Razor/Pages/Depositors/Create.cshtml.cs
using BankDeposits.Domain.Models;
using BankDeposits.Domain.Services.Interfaces;
using BankDeposits.Razor.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BankDeposits.Razor.Pages.Depositors;

public class DepositorCreatePageModel : PageModel
{
    private readonly ILogger<DepositorCreatePageModel> _logger;
    private readonly IDepositorService _depositorService;

    public DepositorCreatePageModel(ILogger<DepositorCreatePageModel> logger, IDepositorService depositorService)
    {
        _logger = logger;
        _depositorService = depositorService;
    }

    [BindProperty]
    public DepositorCreateModel Depositor { get; set; } = new();

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }

        var depositor = new Depositor
        {
            Name = Depositor.Name,
            Surname = Depositor.Surname,
            Patronymic = Depositor.Patronymic,
            PassportSeries = Depositor.PassportSeries,
            PassportNumber = Depositor.PassportNumber,
            Address = Depositor.Address
        };

        if (!await VerifyPassport(depositor.PassportNumber))
        {
            ModelState.AddModelError("Depositor.PassportNumber", "Depositor with this passport already exists");
            return Page();
        }

        await _depositorService.AddAsync(depositor);

        return RedirectToPage("./Index");
    }

    private async Task<bool> VerifyPassport(string passportNumber)
    {
        var depositor = await _depositorService.GetByPassportNumberAsync(passportNumber);
        return depositor is null;
    }
}

src/BankDeposits.Razor/Pages/Depositors/Details.cshtml.cs
using BankDeposits.Domain.Services.Interfaces;
using BankDeposits.Razor.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BankDeposits.Razor.Pages.Depositors;

public class DepositorDetailsPageModel : PageModel
{
    private readonly ILogger<DepositorDetailsPageModel> _logger;
    private readonly IDepositorService _depositorService;

    public DepositorDetailsPageModel(ILogger<DepositorDetailsPageModel> logger, IDepositorService depositorService)
    {
        _logger = logger;
        _depositorService = depositorService;
    }

    public DepositorViewModel Depositor { get; set; } = new();

    public async Task<IActionResult> OnGetAsync(Guid id)
    {
        var depositor = await _depositorService.GetAsync(id);
        Depositor = new DepositorViewModel
        {
            Id = depositor.Id,
            Address = depositor.Address,
            Passport = depositor.Passport,
            FullName = depositor.FullName
        };

        return Page();
    }

    public async Task<IActionResult> OnPostDeleteAsync(Guid id)
    {
        await _depositorService.DeleteAsync(id);
        return RedirectToPage("./Index");
    }
}

src/BankDeposits.Razor/Pages/Depositors/Edit.cshtml.cs
using BankDeposits.Domain.Services.Interfaces;
using BankDeposits.Razor.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BankDeposits.Razor.Pages.Depositors;

public class DepositorEditPageModel : PageModel
{
    private readonly ILogger<DepositorEditPageModel> _logger;
    private readonly IDepositorService _depositorService;

    public DepositorEditPageModel(ILogger<DepositorEditPageModel> logger, IDepositorService depositorService)
    {
        _logger = logger;
        _depositorService = depositorService;
    }

    [BindProperty]
    public DepositorEditModel Depositor { get; set; } = new();

    public async Task<IActionResult> OnGetAsync(Guid id)
    {
        var depositor = await _depositorService.GetAsync(id);
        Depositor = new DepositorEditModel
        {
            Id = depositor.Id,
            Name = depositor.Name,
            Surname = depositor.Surname,
            Patronymic = depositor.Patronymic,
            Address = depositor.Address,
        };

        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }

        var depositor = await _depositorService.GetAsync(Depositor.Id);

        depositor.Name = Depositor.Name;
        depositor.Surname = Depositor.Surname;
        depositor.Patronymic = Depositor.Patronymic;
        depositor.Address = Depositor.Address;

        await _depositorService.UpdateAsync(depositor);

        return RedirectToPage("./Details", new { id = Depositor.Id });
    }
}

src/BankDeposits.Razor/Pages/Deposits/Create.cshtml.cs
using BankDeposits.Domain.Models;
using BankDeposits.Domain.Services.Interfaces;
using BankDeposits.Razor.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Caching.Memory;

namespace BankDeposits.Razor.Pages.Deposits;

public class DepositsCreatePageModel : PageModel
{
    private readonly ILogger<DepositsCreatePageModel> _logger;
    private readonly IDepositService _depositService;
    private readonly IAccountService _accountService;
    private readonly IMemoryCache _memoryCache;

    public DepositsCreatePageModel(ILogger<DepositsCreatePageModel> logger, IDepositService depositService, IAccountService accountService, IMemoryCache memoryCache)
    {
        _logger = logger;
        _depositService = depositService;
        _accountService = accountService;
        _memoryCache = memoryCache;
    }

    [BindProperty]
    public DepositCreateModel Deposit { get; set; } = new();

    public SelectList Accounts { get; set; } = default!;

    public async Task OnGetAsync() => await PopulateAccountsAsync();

    public async Task<IActionResult> OnPostAsync()
    {
        if (ModelState.IsValid)
        {
            var deposit = new Deposit
            {
                AccountId = Deposit.AccountId,
                Amount = Deposit.Amount,
                StartDate = Deposit.StartDate,
                EndDate = Deposit.EndDate,
                Rate = Deposit.Rate
            };

            await _depositService.AddAsync(deposit);

            return RedirectToPage("./Index");
        }

        await PopulateAccountsAsync();
        return Page();
    }

    private async Task PopulateAccountsAsync()
    {
        if (!_memoryCache.TryGetValue("AccountsList", out SelectList? cachedAccounts))
        {
            var accounts = await _accountService.GetAllAsync();
            cachedAccounts = new SelectList(accounts, nameof(Account.Id), nameof(Account.Number));
            _memoryCache.Set("AccountsList", cachedAccounts, TimeSpan.FromMinutes(5));
        }

        Accounts = cachedAccounts!;
    }
}

src/BankDeposits.Razor/Pages/Deposits/Details.cshtml.cs
using BankDeposits.Domain.Services.Interfaces;
using BankDeposits.Razor.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BankDeposits.Razor.Pages.Deposits;

public class DepositDetailsPageModel : PageModel
{
    private readonly ILogger<DepositDetailsPageModel> _logger;
    private readonly IDepositService _depositService;

    public DepositDetailsPageModel(ILogger<DepositDetailsPageModel> logger, IDepositService depositService)
    {
        _logger = logger;
        _depositService = depositService;
    }

    public DepositViewModel Deposit { get; set; } = new();

    public async Task<IActionResult> OnGetAsync(Guid id)
    {
        var deposit = await _depositService.GetAsync(id);
        Deposit = new DepositViewModel
        {
            Id = deposit.Id,
            Amount = deposit.Amount,
            StartDate = deposit.StartDate,
            Rate = deposit.Rate,
            EndDate = deposit.EndDate,
            Profit = deposit.Profit,
            AccountId = deposit.AccountId
        };
        return Page();
    }

    public async Task<IActionResult> OnPostDeleteAsync(Guid id)
    {
        await _depositService.DeleteAsync(id);
        return RedirectToPage("./Index");
    }
}

src/BankDeposits.Razor/Pages/Deposits/Edit.cshtml.cs
using BankDeposits.Domain.Services.Interfaces;
using BankDeposits.Razor.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BankDeposits.Razor.Pages.Deposits;

public class DepositsEditPageModel : PageModel
{
    private readonly ILogger<DepositsEditPageModel> _logger;
    private readonly IDepositService _depositService;

    public DepositsEditPageModel(ILogger<DepositsEditPageModel> logger, IDepositService depositService)
    {
        _logger = logger;
        _depositService = depositService;
    }

    [BindProperty]
    public DepositEditModel Deposit { get; set; } = new();

    public async Task<IActionResult> OnGetAsync(Guid id)
    {
        var deposit = await _depositService.GetAsync(id);
        Deposit = new DepositEditModel
        {
            Id = deposit.Id,
            Rate = deposit.Rate,
        };
        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }

        var deposit = await _depositService.GetAsync(Deposit.Id);

        deposit.Rate = Deposit.Rate;

        await _depositService.UpdateAsync(deposit);

        return RedirectToPage("./Details", new { id = Deposit.Id });
    }
}

src/BankDeposits.Razor/Pages/Deposits/Index.cshtml.cs
using BankDeposits.Domain.Services.Interfaces;
using BankDeposits.Razor.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BankDeposits.Razor.Pages.Deposits;

public class DepositsIndexPageModel : PageModel
{
    private readonly ILogger<DepositsIndexPageModel> _logger;
    private readonly IDepositService _depositService;

    public DepositsIndexPageModel(ILogger<DepositsIndexPageModel> logger, IDepositService depositService)
    {
        _logger = logger;
        _depositService = depositService;
    }

    public IList<DepositViewModel> Deposits { get; set; } = new List<DepositViewModel>();

    public async Task<IActionResult> OnGetAsync()
    {
        var deposits = await _depositService.GetAllAsync();

        Deposits = deposits.Select(x => new DepositViewModel
        {
            Id = x.Id,
            AccountId = x.AccountId,
            StartDate = x.StartDate,
            EndDate = x.EndDate,
            Rate = x.Rate,
            Amount = x.Amount,
            Profit = x.Profit
        }).ToList();

        return Page();
    }
}

src/BankDeposits.Razor/Pages/Deposits/Create.cshtml
@page
@model BankDeposits.Razor.Pages.Deposits.DepositsCreatePageModel

@{
    ViewData["Title"] = "Create Deposit";
}

<h1>@ViewData["Title"]</h1>

<div class="container">
    <form method="post">
        <div class="form-group">
            <label asp-for="Deposit.Amount" class="control-label"></label>
            <input asp-for="Deposit.Amount" class="form-control"/>
            <span asp-validation-for="Deposit.Amount" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Deposit.Rate" class="control-label"></label>
            <input asp-for="Deposit.Rate" class="form-control"/>
            <span asp-validation-for="Deposit.Rate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Deposit.StartDate"></label>
            <input asp-for="Deposit.StartDate" class="form-control" type="date"/>
            <span asp-validation-for="Deposit.StartDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Deposit.EndDate" class="control-label"></label>
            <input asp-for="Deposit.EndDate" class="form-control" type="date"/>
            <span asp-validation-for="Deposit.EndDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Deposit.AccountId" class="control-label"></label>
            <select asp-for="Deposit.AccountId" class="form-control" asp-items="Model.Accounts">
                <option value="">-- Select Account --</option>
            </select>
            <span asp-validation-for="Deposit.AccountId" class="text-danger"></span>
        </div>

        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary"/>
        </div>
    </form>
</div>

src/BankDeposits.Razor/Pages/Deposits/Details.cshtml
@page "{id:guid}"
@model BankDeposits.Razor.Pages.Deposits.DepositDetailsPageModel

@{
    ViewData["Title"] = "Details";
}

<h1>@ViewData["Title"]</h1>

<div class="container mb-3">
    <div class="row">
        <dl class="dl-horizontal">
            <dt>@Html.DisplayNameFor(model => model.Deposit.Id)</dt>
            <dd>@Html.DisplayFor(model => model.Deposit.Id)</dd>
            <dt>@Html.DisplayNameFor(model => model.Deposit.AccountId)</dt>
            <dd>@Html.DisplayFor(model => model.Deposit.AccountId)</dd>
            <dt>@Html.DisplayNameFor(model => model.Deposit.Amount)</dt>
            <dd>@Html.DisplayFor(model => model.Deposit.Amount)</dd>
            <dt>@Html.DisplayNameFor(model => model.Deposit.StartDate)</dt>
            <dd>@Html.DisplayFor(model => model.Deposit.StartDate)</dd>
            <dt>@Html.DisplayNameFor(model => model.Deposit.EndDate)</dt>
            <dd>@Html.DisplayFor(model => model.Deposit.EndDate)</dd>
            <dt>@Html.DisplayNameFor(model => model.Deposit.Rate)</dt>
            <dd>@Html.DisplayFor(model => model.Deposit.Rate)</dd>
            <dt>@Html.DisplayNameFor(model => model.Deposit.Profit)</dt>
            <dd>@Html.DisplayFor(model => model.Deposit.Profit)</dd>
        </dl>
    </div>

    <div class="row">
        <div class="col-md-4">
            <a asp-page="Edit" asp-route-id="@Model.Deposit.Id" class="btn btn-primary">Edit</a>
            <a asp-page="Index" class="btn btn-primary">Back to List</a>

            <form method="post" asp-page-handler="Delete" asp-route-id="@Model.Deposit.Id" onsubmit="return confirm('Are you sure you want to delete this item?');">
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </div>
    </div>
</div>

src/BankDeposits.Razor/Pages/Deposits/Edit.cshtml
@page
@model BankDeposits.Razor.Pages.Deposits.DepositsEditPageModel

@{
    ViewData["Title"] = "Edit";
}

<h1>@ViewData["Title"]</h1>

<div class="container">
    <form method="post">
        <input type="hidden" asp-for="Deposit.Id"/>

        <div class="form-group">
            <label asp-for="Deposit.Rate" class="control-label"></label>
            <input asp-for="Deposit.Rate" class="form-control"/>
            <span asp-validation-for="Deposit.Rate" class="text-danger"></span>
        </div>

        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary"/>
        </div>
    </form>
</div>

src/BankDeposits.Razor/Pages/Deposits/Index.cshtml
@page
@model BankDeposits.Razor.Pages.Deposits.DepositsIndexPageModel

@{
    ViewData["Title"] = "Deposits List";
}

<h1 class="display-4 mb-4">@ViewData["Title"]</h1>

<a asp-page="Create" class="btn btn-primary mb-3">Create New</a>

<div class="container mt-3">
    <table class="table table-striped table-responsive-md table-hover shadow">
        <thead class="thead-dark">
        <tr>
            <th>Id</th>
            <th>Account Id</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Rate</th>
            <th>Amount</th>
            <th>Profit</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var deposit in Model.Deposits)
        {
            <tr>
                <td>@deposit.Id</td>
                <td>@deposit.AccountId</td>
                <td>@deposit.StartDate</td>
                <td>@deposit.EndDate</td>
                <td>@deposit.Rate</td>
                <th>@deposit.Amount</th>
                <th>@deposit.Profit</th>
                <th>
                    <a asp-page="./Details" asp-route-id="@deposit.Id" class="btn btn-primary">Details</a>
                </th>
            </tr>
        }
        </tbody>
    </table>
</div>